/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioMessage: typeof import('./../components/Message/components/AudioMessage.vue')['default']
    CardMessage: typeof import('./../components/Message/components/CardMessage.vue')['default']
    ChatSidebar: typeof import('./../components/ChatSidebar.vue')['default']
    ChatTabContent: typeof import('./../components/ChatTabContent.vue')['default']
    ChatWindow: typeof import('./../components/ChatWindow.vue')['default']
    EditableInput: typeof import('./../components/EditableInput.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    ImageMessage: typeof import('./../components/Message/components/ImageMessage.vue')['default']
    LinkMessage: typeof import('./../components/Message/components/LinkMessage.vue')['default']
    Main: typeof import('./../components/chat/Main.vue')['default']
    MessageComponent: typeof import('./../components/chat/MessageComponent.vue')['default']
    MessagesList: typeof import('./../components/chat/MessagesList.vue')['default']
    RedEnvelopeMessage: typeof import('./../components/Message/components/RedEnvelopeMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextMessage: typeof import('./../components/Message/components/TextMessage.vue')['default']
    TransferMessage: typeof import('./../components/Message/components/TransferMessage.vue')['default']
    Tree: typeof import('./../components/Tree.vue')['default']
    UnknownMessage: typeof import('./../components/Message/components/UnknownMessage.vue')['default']
    VideoMessage: typeof import('./../components/Message/components/VideoMessage.vue')['default']
  }
}
